services:
  # Database
  db:
    platform: linux/x86_64
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
      # - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: auth
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - net1

  # web
  web:
    depends_on:
      - db
    image: registry.nipa.cloud/kmitl-registry/amongus-front-back:1.0.0
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: mysql://root:${MYSQL_ROOT_PASSWORD}@db:3306/auth
    networks:
      - net1

networks:
  net1:

volumes:
  db_data:
